- name: check for apache
  shell: "service cosul status"
  register: _svc_cosul
  failed_when: >
    _svc_apache.rc != 0 and ("unrecognized service" not in _svc_apache.stderr)

- name: Install cosul Data-dog Plugin
  include: cosul.yml
  when: "_svc_cosul.rc == 0"