- name: check for consul
  shell: "service consul status"
  register: _svc_consul
  failed_when: >
    _svc_consul.rc != 0 and ("unrecognized service" not in _svc_apache.stderr)

- name: Install consul Data-dog Plugin
  include: consul.yml
  when: "_svc_consul.rc == 0"