#Datadog_agent
---
- name: Install datadog agent
  shell: DD_API_KEY={{ api_key }} bash -c "$(curl -L https://raw.githubusercontent.com/DataDog/dd-agent/master/packaging/datadog-agent/source/install_agent.sh)"
  register: datadog_enabled

- template: src=process.yaml dest=/etc/dd-agent/conf.d/process.yaml
  notify: restart datadog-agent


