#data_dog Main yml file
---
- hosts: servers
  become: true
  roles:
    - role: datadog_agent
    #- role: docker
    #- role: kafka
    #- role: cassandra
    #- role: consul
    #- role: elasticsearch
    #- role: mysql
    
