  init_config:

  instances:
    - server: {{ mysql_host }}
      user: {{ mysql_datadog_user }}
      pass: {{ mysql_datadog_user_password }}# from the CREATE USER step earlier
      port: {{ mysql_port }} # e.g. 3306
      options:
          replication: 0
          galera_cluster: 1
          extra_status_metrics: true
          extra_innodb_metrics: true
          extra_performance_metrics: true
          schema_size_metrics: false
          disable_innodb_metrics: false
