- name: check for apache
  shell: "service mysql status"
  register: _svc_mysql
  failed_when: >
    _svc_apache.rc != 0 and ("unrecognized service" not in _svc_apache.stderr)

- name: Install mysql Data-dog Plugin
  include: mysql.yml
  when: "_svc_mysql.rc == 0"