- name: check for docker
  shell: "service docker status"
  register: _svc_docker
  failed_when: >
    _svc_docker.rc != 0 and ("unrecognized service" not in _svc_apache.stderr)

- name: Install docker Data-dog Plugin
  include: docker.yml
  when: "_svc_docker.rc == 0"