- template: src=data_agent_coreos.yaml dest=/etc/dd-agent/conf.d/data_agent_coreos.yaml
  notify: restart datadog-agent

- name: restart datadog-agent
  action: service name=datadog-agent state=restarted