---
- name: Run the following command to set the api key
  command: docker run -d --privileged --name dd-agent -h hostname` -v /var/run/docker.sock:/var/run/docker.sock -v /proc/mounts:/host/proc/mounts:ro -v /sys/fs/cgroup/:/host/sys/fs/cgroup:ro -e API_KEY={{ api_key }} datadog/docker-dd-agent
 
